export const CATEGORIES = {
  STYLE: '界面美化',
  TRANSLATION: '翻译功能',
  ENHANCEMENT: '增强功能',
} as const;

export interface FeatureConfig {
  enabled: boolean;
  handler: (() => void) | null;
  name: string;
  category: keyof typeof CATEGORIES;
  description: string;
}

export const FEATURES: Record<string, FeatureConfig> = {
  UI: {
    enabled: true,
    handler: null,
    name: '基础样式美化',
    category: 'STYLE',
    description: '优化网站的基础背景、导航栏及卡牌样式。',
  },
  FILTER_STYLE: {
    enabled: true,
    handler: null,
    name: '筛选器美化',
    category: 'STYLE',
    description: '美化筛选器外观，使其更加现代且易于使用。',
  },
  RUNE: {
    enabled: true,
    handler: null,
    name: '死亡骑士符文美化',
    category: 'STYLE',
    description: '为死亡骑士职业的卡牌添加精美的符文颜色标识。',
  },
  MANA: {
    enabled: true,
    handler: null,
    name: '法力水晶美化',
    category: 'STYLE',
    description: '将法力水晶数值替换为更具质感的图形化图标。',
  },
  TITLE_STYLE: {
    enabled: true,
    handler: null,
    name: '页面主标题样式美化',
    category: 'STYLE',
    description: '优化主标题的字体大小、颜色及排版样式。',
  },
  SUB_STYLE: {
    enabled: true,
    handler: null,
    name: '页面副标题样式美化',
    category: 'STYLE',
    description: '为副标题添加更美观的样式修饰。',
  },
  TABLE_STYLE: {
    enabled: true,
    handler: null,
    name: '表格样式美化',
    category: 'STYLE',
    description: '优化表格的行高、背景色及边框，提升阅读体验。',
  },
  BASIC: {
    enabled: true,
    handler: null,
    name: '基础UI翻译',
    category: 'TRANSLATION',
    description: '翻译页面中基础的导航项、按钮及通知文字。',
  },
  FILTER: {
    enabled: true,
    handler: null,
    name: '筛选器翻译',
    category: 'TRANSLATION',
    description: '对卡组列表中的格式、排名、职业等筛选条件进行中文翻译。',
  },
  SEARCH: {
    enabled: true,
    handler: null,
    name: '搜索框翻译',
    category: 'TRANSLATION',
    description: '为卡牌数据库的搜索框提供中文翻译支持。',
  },
  DECK: {
    enabled: true,
    handler: null,
    name: '卡组名称翻译',
    category: 'TRANSLATION',
    description: '对卡组详情页的卡组名称进行规则化翻译。',
  },
  CARD: {
    enabled: true,
    handler: null,
    name: '卡牌名称翻译',
    category: 'TRANSLATION',
    description: '将卡牌数据库及卡组中的英文卡名替换为官方中文名称。',
  },
  TAG: {
    enabled: true,
    handler: null,
    name: '卡组局数标签翻译',
    category: 'TRANSLATION',
    description: '在卡组列表上翻译局数、胜率等标签文字。',
  },
  TITLE: {
    enabled: true,
    handler: null,
    name: '页面主标题翻译',
    category: 'TRANSLATION',
    description: '翻译各个页面的主标题，如"Decks"、"Meta"等。',
  },
  SUB: {
    enabled: true,
    handler: null,
    name: '页面副标题翻译',
    category: 'TRANSLATION',
    description: '翻译页面中的副标题及相关辅助说明文字。',
  },
  TABLE: {
    enabled: true,
    handler: null,
    name: '表格翻译',
    category: 'TRANSLATION',
    description: '翻译数据表格中的表头、统计项及内容文字。',
  },
  AD: {
    enabled: true,
    handler: null,
    name: '广告移除',
    category: 'ENHANCEMENT',
    description: '自动隐藏页面中影响阅读的各种广告位。',
  },
  CARD_LINK: {
    enabled: true,
    handler: null,
    name: '移除卡牌超链接',
    category: 'ENHANCEMENT',
    description: '移除卡组列表中可能干扰操作的卡牌名称超链接。',
  },
  CLIPBOARD: {
    enabled: true,
    handler: null,
    name: '卡组复制按钮增强',
    category: 'ENHANCEMENT',
    description: '增强卡组代码复制功能，提供更友好的交互提示。',
  },
  SCROLL_TOP: {
    enabled: true,
    handler: null,
    name: '返回顶部按钮',
    category: 'ENHANCEMENT',
    description: '在页面右下角添加一个悬浮按钮，点击可快速返回页面顶部。',
  },
};

export const SELECTORS = {
  DECK_TITLE: 'h2.deck-title > span > a',
  DECK_LINK: 'a.deck-title',
  BASIC_DECK_TITLE: 'a.basic-black-text.deck-title',
  CARD_NAME: 'div.card-name.deck-text',
  NAV_BASE: '#burger-toggle > div.navbar-start',
  MANA_CRYSTAL:
    '.card-number.deck-text.decklist-card-background.is-unselectable.has-text-left[style="width: 3ch"]',
} as const;

export const DEFAULT_CLASS_ACCENT = '#9a8768';
export const DEFAULT_CLASS_BG = 'rgba(154, 135, 104, 0.10)';

export const CLASS_ACCENT_COLORS: Record<string, string> = {
  deathknight: '#c51e35',
  demonhunter: '#5aa832',
  druid: '#c67a2d',
  hunter: '#5a9f44',
  mage: '#36b9d4',
  paladin: '#d8c936',
  priest: '#b8ad98',
  rogue: '#d3b63b',
  shaman: '#1581cf',
  warlock: '#a931c7',
  warrior: '#bf8a55',
};

export const CLASS_BG_COLORS: Record<string, string> = {
  deathknight: 'rgba(197, 30, 53, 0.13)',
  demonhunter: 'rgba(90, 168, 50, 0.13)',
  druid: 'rgba(198, 122, 45, 0.13)',
  hunter: 'rgba(90, 159, 68, 0.13)',
  mage: 'rgba(54, 185, 212, 0.13)',
  paladin: 'rgba(216, 201, 54, 0.13)',
  priest: 'rgba(184, 173, 152, 0.13)',
  rogue: 'rgba(211, 182, 59, 0.13)',
  shaman: 'rgba(21, 129, 207, 0.13)',
  warlock: 'rgba(169, 49, 199, 0.13)',
  warrior: 'rgba(191, 138, 85, 0.13)',
};

export const BASE_URL = 'https://www.hsguru.com/';

export const ROUTES = {
  DECKS: '/decks',
  DECKS_QUERY: '/decks?',
  DECK_BUILDER: '/deckbuilder',
  CARD_STATS: '/card-stats',
  CARD_STATS_QUERY: '/card-stats?',
  CARD_STATS_BY_ARCHETYPE: '/card-stats?archetype=',
  ARCHETYPE: '/archetype/',
  REPLAYS: '/replays',
  REPLAYS_QUERY: '/replays?',
  REPLAYS_WITH_URL: '/replays?has_replay_url=true',
  REPLAYS_BY_ARCHETYPE: '/replays?archetype=',
  DECK_DETAIL: '/deck/',
  LEADERBOARD: '/leaderboard',
  LEADERBOARD_PLAYER_STATS: '/leaderboard/player-stats',
} as const;

export const DATASET = {
  CLIPBOARD_TEXT: 'data-clipboard-text',
  ARIA_ON_COPY: 'data-aria-on-copy',
  BALLOON_POS: 'data-balloon-pos',
  ORIGINAL: 'data-original',
  TYPE: 'data-type',
  TAB: 'data-tab',
} as const;

export const UI_TEXT = {
  COPY_SUCCESS_TOAST: '卡组代码已复制',
  COPY_SUCCESS_LABEL: '卡组代码已复制',
  COPY_DEFAULT_LABEL: '复制',
  NO_RANK: '暂无排名',
  LOW_SAMPLE: '样本不足',
  SEPARATOR: '/',
  EMPTY_CARD_LIST: '暂无待翻译的',
  CARD_TYPE: '卡牌',
  DECK_TYPE: '卡组',
  NAME_PLACEHOLDER: '名称',
  TRANSLATION_PLACEHOLDER: '输入中文翻译',
  DELETE: '删除',
  SAVE: '保存',
  CANCEL: '取消',
  ADD: '添加',
  MERGE: '合并',
  SETTINGS: '设置',
  CLOSE: '关闭',
  RESET: '重置',
  CONFIRM: '确认',
  LOADING: '加载中...',
  ERROR: '错误',
  SUCCESS: '成功',
} as const;

export const CLASSES = {
  DECK_CARD_SHELL: 'hsguru-deck-card-shell',
  DECK_SUMMARY: 'hsguru-deck-summary',
  DECK_SUMMARY_ROW: 'hsguru-deck-summary-row',
  DECK_SUMMARY_TITLE: 'hsguru-deck-summary-title',
  HIDDEN_DECK_CODE: 'hsguru-hidden-deck-code',
  DECK_ICON_BUTTON: 'hsguru-deck-icon-button',
  DECK_DUST_BAR: 'hsguru-deck-dust-bar',
  COPY_TOAST: 'hsguru-copy-toast',
  COPY_SUCCESS: 'hsguru-copy-success',
  STREAMER_FILTERS: 'hsguru-streamer-filters',
  LEADERBOARD_FILTERS: 'hsguru-leaderboard-filters',
  LEADERBOARD_NAV_BUTTON: 'hsguru-leaderboard-nav-button',
  LEADERBOARD_SEARCH_FORM: 'hsguru-leaderboard-search-form',
  LEADERBOARD_SEARCH_INPUT: 'hsguru-leaderboard-search-input',
  LEADERBOARD_INLINE_INPUT: 'hsguru-leaderboard-inline-input',
  LEADERBOARD_INLINE_FORM: 'hsguru-leaderboard-inline-form',
  LEADERBOARD_INLINE_FIELD: 'hsguru-leaderboard-inline-field',
  META_TABLE: 'hsguru-meta-table',
  META_ARCHETYPE_CELL: 'hsguru-meta-archetype-cell',
  STREAMER_DECKS_TABLE: 'hsguru-streamer-decks-table',
  STREAMER_DECK_CELL: 'hsguru-streamer-deck-cell',
  STREAMER_EMPTY_RANK: 'hsguru-streamer-empty-rank',
  MATCHUPS_WRAPPER: 'hsguru-matchups-wrapper',
  MATCHUPS_TABLE: 'hsguru-matchups-table',
  MATCHUPS_ACTION: 'hsguru-matchups-action',
  MATCHUPS_ACTION_WINRATE: 'hsguru-matchups-action-winrate',
  MATCHUPS_ACTION_FILL: 'hsguru-matchups-action-fill',
  MATCHUPS_ACTION_RESET: 'hsguru-matchups-action-reset',
  MATCHUPS_ACTION_USAGE: 'hsguru-matchups-action-usage',
  MATCHUPS_ACTION_ARCHETYPE: 'hsguru-matchups-action-archetype',
  MATCHUPS_META_HEADER: 'hsguru-matchups-meta-header',
  MATCHUPS_META_SEPARATOR: 'hsguru-matchups-meta-separator',
  MATCHUPS_CORNER_CELL: 'hsguru-matchups-corner-cell',
  MATCHUPS_DECK_HEADER: 'hsguru-matchups-deck-header',
  MATCHUPS_STICKY_COL: 'hsguru-matchups-sticky-col',
  MATCHUPS_WINRATE_CELL: 'hsguru-matchups-winrate-cell',
  MATCHUPS_STICKY_COL_2: 'hsguru-matchups-sticky-col-2',
  MATCHUPS_ARCHETYPE_CELL: 'hsguru-matchups-archetype-cell',
  MATCHUPS_DECK_CELL: 'hsguru-matchups-deck-cell',
  MATCHUPS_HEAT_CELL: 'hsguru-matchups-heat-cell',
  MATCHUPS_LOW_SAMPLE: 'hsguru-matchups-low-sample',
  SCROLL_TOP: 'hsguru-scroll-top',
  CARD_PREVIEW: 'hsguru-chinese-card-preview',
  HIDE_NATIVE_PREVIEW: 'hsguru-hide-native-card-preview',
  FEATURE_CARD: 'hsguru-feature-card',
  FEATURE_INFO: 'hsguru-feature-info',
  FEATURE_NAME: 'hsguru-feature-name',
  MODAL_TITLE: 'hsguru-modal-title',
  SIDEBAR_TITLE: 'hsguru-sidebar-title',
  TAB_ITEM: 'hsguru-tab-item',
  TAB_CONTENT: 'hsguru-tab-content',
  TAB_ACTIVE: 'active',
  CHECKBOX: 'hsguru-checkbox',
  CUSTOM_ITEM_CHECKBOX: 'custom-item-checkbox',
  CUSTOM_TRANSLATION_ITEM: 'custom-translation-item',
  CUSTOM_TRANSLATION_INPUT: 'custom-translation-input',
  DELETE_BTN: 'hsguru-delete-btn',
  INPUT: 'hsguru-input',
  PANEL: 'hsguru-panel',
  PANEL_HEADER: 'hsguru-panel-header',
  PANEL_BODY: 'hsguru-panel-body',
  PANEL_TITLE: 'hsguru-panel-title',
  PANEL_CLOSE: 'hsguru-panel-close',
  PANEL_TABS: 'hsguru-panel-tabs',
  SETTINGS_SECTION: 'hsguru-settings-section',
  SETTINGS_TITLE: 'hsguru-settings-title',
  SETTINGS_DESC: 'hsguru-settings-desc',
  SETTINGS_ITEM: 'hsguru-settings-item',
  SETTINGS_LABEL: 'hsguru-settings-label',
  SETTINGS_HINT: 'hsguru-settings-hint',
  SETTINGS_TOGGLE: 'hsguru-settings-toggle',
  SETTINGS_SAVE: 'hsguru-settings-save',
  SETTINGS_CANCEL: 'hsguru-settings-cancel',
  SETTINGS_RESET: 'hsguru-settings-reset',
  SETTINGS_SAVE_BTN: 'hsguru-save-btn',
  SETTINGS_CANCEL_BTN: 'hsguru-cancel-btn',
  SETTINGS_RESET_BTN: 'hsguru-reset-btn',
} as const;

export const API = {
  CARD_TRANSLATION: 'https://api2.iyingdi.com/hearthstone/card/search/vertical',
  FIRESTONE: 'https://www.firestoneapp.com/',
  BLIZZARD: 'hearthstone.blizzard.com',
} as const;

export const staticPrefix: Record<string, string> = {
  'Splendiferous Whizbang': '酷炫的威兹班',
  'No Minion': '无随从',
  'End of Turnadin': '回合结束骑',
  'Tick Tock': '提克和托克',
  Harold: '兆示',
  Control: '控制',
  Egglock: '蛋术',
  Merithra: '麦琳瑟拉',
  Egg: '蛋',
  Broxigar: '布洛克加斯',
  Kingslayer: '弑君者',
  Discolock: '弃牌术',
  CtA: '战斗号角',
  Seedlock: '任务术',
  Lynessa: '莱妮莎',
  Boar: '猪猪',
  Plague: '瘟疫',
  Gladiator: '角斗',
  Rafaamlock: '拉法姆术',
  'No Hand': '无牌',
  Burn: '火焰',
  Beast: '野兽',
  Mech: '机械',
  Dragon: '龙',
  Elemental: '元素',
  Demon: '恶魔',
  Draenei: '德莱尼',
  Pirate: '海盗',
  Murloc: '鱼人',
  Undead: '亡灵',
  Protoss: '星灵',
  Terran: '人族',
  Zerg: '异虫',
  Unholy: '邪恶',
  Blood: '鲜血',
  Frost: '冰',
  Arcane: '奥术',
  Shadow: '暗影',
  Fel: '邪能',
  Taunt: '嘲讽',
  Deathrattle: '亡语',
  Weapon: '武器',
  Secret: '奥秘',
  Location: '地标',
  Spell: '法术',
  Starship: '星舰',
  Enrage: '激怒',
  Copy: '复制',
  Odd: '奇数',
  Even: '偶数',
  Questline: '任务',
  Quest: '任务',
  Discover: '发现',
  Outcast: '流放',
  Aura: '光环',
  Combo: '连击',
  Imbue: '灌注',
  Libram: '圣契',
  Corpse: '残骸',
  Handbuff: '污手',
  HL: '宇宙',
  Highlander: '宇宙',
  XL: '40',
  STD: '标准',
  Other: '其他',
  Aggro: '快攻',
  Armor: '叠甲',
  Bounce: '减费',
  Defense: '防御',
  Damage: '伤害',
  Pain: '自伤',
  Cycle: '过牌',
  Fatigue: '疲劳',
  Mill: '洗牌',
  Thief: '偷窃',
  Miracle: '奇迹',
  Deckless: '无牌',
  Token: '衍生物',
  Topdeck: '顶牌',
  Endseer: '爆牌',
};

export const classSuffix: Record<string, string> = {
  Warlock: '术',
  Druid: '德',
  Priest: '牧',
  Rogue: '贼',
  Mage: '法',
  Hunter: '猎',
  Paladin: '骑',
  Shaman: '萨',
  Warrior: '战',
  DH: '瞎',
  DK: '死骑',
};

export const STORAGE_PREFIX = {
  CONFIG: 'hsguru_config',
  CUSTOM_DECK: 'hsguru_custom_deck_names',
  CUSTOM_CARD: 'hsguru_custom_card_names',
  CARD_TRANSLATION: 'hsguru_card_',
  CARD_IMAGE: 'hsguru_card_image_',
  CACHE_MIGRATED: 'hsguru_cache_migrated',
  DATA_MIGRATED: 'hsguru_data_migrated',
} as const;

export const MAX_CONCURRENT_REQUESTS = 2;
export const REQUEST_DELAY = 500;

export const BUTTON_TITLES: Record<string, string> = {
  Winrate: '按胜率排序',
  'Seed Weights': '按当前使用率填充权重',
  'Reset Weights': '重置自定义权重',
  Popularity: '按使用率排序',
  Archetype: '按卡组职业排序',
};

export const SIMPLE_URL_TITLE_MAP: Record<string, string> = {
  'leaderboard/player-stats': 'Leaderboard Stats',
  leaderboard: 'Leaderboard',
  decks: 'Decks',
  meta: 'Meta',
  matchups: 'Matchups',
  'streamer-decks': 'Streamer Decks',
  esports: 'Esports',
  deckbuilder: 'Hearthstone DeckBuilder',
  cards: 'Hearthstone Cards',
  'legacy-hsesports': 'Archive of old hsesports pages',
  replays: 'Replays',
  'battlefy/third-party-tournaments': 'Choose organization',
  'battlefy/tournaments-stats': 'Tournaments Stats',
  'streaming-now': 'Streaming Now',
  'streamer-instructions': 'Streamer Instructions',
  'hdt-plugin': 'HDT Plugin',
  'stats/explanation': 'Stats Explanation',
};

export const AD_ELEMENT_IDS = [
  'nitropay-sticky-side-rail-container',
  'below-title-ads',
  'nitropay-below-title-leaderboard',
  'nitropay-floating-video-all',
  'nitro-float-close',
  'nitropay-sticky-side-rail',
  'nitropay-sticky-side-rail-close',
  'nitropay-desktop-anchor',
  'nitropay-desktop-anchor-close',
] as const;

export const RUNE_TYPES = { B: 'blood', F: 'frost', U: 'unholy' } as const;

export const FILTER_LIST_CONFIGS = {
  format: ['Standard', 'Wild'],
  rank: [
    'Top 100',
    'Top 200',
    'Top 500',
    'Top 1000',
    'Top 5000',
    'Top 1k',
    'Top 5k',
    'Legend',
    'Diamond 4-1',
    'Diamond-Legend',
    'All',
  ],
  class: [
    'Player Class',
    'Any Class',
    'Opponent Class',
    'Death Knight',
    'Demon Hunter',
    'Druid',
    'Hunter',
    'Mage',
    'Paladin',
    'Priest',
    'Rogue',
    'Shaman',
    'Warlock',
    'Warrior',
  ],
  vsClass: [
    'Any Class',
    "Opponent's Class",
    'VS Death Knight',
    'VS Demon Hunter',
    'VS Druid',
    'VS Hunter',
    'VS Mage',
    'VS Paladin',
    'VS Priest',
    'VS Rogue',
    'VS Shaman',
    'VS Warlock',
    'VS Warrior',
  ],
} as const;

export const IMPACT_TYPES = [
  'Mulligan Impact',
  'Drawn Impact',
  'Not Drawn Impact',
  'Kept Impact',
] as const;

export const COUNT_TYPES = [
  'Card',
  'Mulligan Count',
  'Drawn Count',
  'Not Drawn Count',
  'Kept Count',
] as const;
